### ISSUE TITLE
Meslo-Monaco confusion

### ISSUE THREAD

**Issue by belluzj** [john2x/fontsforcoding#1]
The screenshots of Meslo LG actually feature the Monaco typeface.

Apart from that the site looks good, and thanks for including my font :) You might also want to include Inconsolata and Monaco, which look extremely nice too!

**Comment by john2x** [comment]
Oh, I thought it was strange how it looked more like Monaco instead of Menlo. Fixed and added Inconsolata and Monaco. Thanks!
